---
title: "Analysis Report"
output:
  html_document:
    toc: false
    toc_float: false
    theme: flatly
params:
  selected_disag_vals: NULL
  selected_questions: NULL
  data_file: NULL
  
editor_options:
  chunk_output_type: console
---

# {.tabset}


```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(readxl)
library(tidyverse)
source('src/functions.R', local=T)
source('src/Mode.R', local=T)
source('src/process_data_for_aggregation.R', local=T)
source('src/aggregate_data.R', local=T)
source('src/format.R', local=T)
source('src/utils.R', local=T)
# Set global chunk options
knitr::opts_chunk$set(
  echo = FALSE,      # Hide code in the output
  eval = TRUE,       # Ensure all code is executed
  message = FALSE,   # Suppress messages (e.g., from loading packages)
  warning = FALSE,   # Suppress warnings in the output
  results = 'asis',  # Allow raw markdown output (useful for cat())
  # fig.align = "center", # Center align figures
  fig.width = 10,    # Default figure width
  fig.height = 5     # Default figure height
)



# Load Data

# test <- data %>% 
#   filter(str_detect(label, "what are the main reason")) %>% 
#   filter(disag_val_1=="SS0202") %>% 
#   pull(label)
# %>% 
#   mutate(mean = mean * 100) 
# %>% 
#     filter(label %in% params$selected_questions, disag_val_1 %in% params$selected_disag_vals)
local <- F


if (local==T){
data <- read_excel(list.files('input', pattern="analysis_data_test", full.names = TRUE)) 
params <- NULL
params$selected_disag_vals <- c("SS0202", "SS0103", "SS0102")
params$selected_questions <- "What are the main problems with water in ${info_settlement_final}?"
params$selected_questions <- "For the displaced people who have arrived in ${info_settlement_final}, what are the main reasons that they left their homes?"
print(params$selected_disag_vals)
print(params$selected_questions)
print(head(data))  # Check if data is being read properly


print(unique(data$label))
print(unique(params$selected_questions))

}else{
  data <- readRDS(params$data_file)
}
# Initialize lists to store plots
plots_disag_val <- list()
plots_indicator <- list()
```


```{r Area plots, results='asis'}
# Main tabset for 'By Disag-Val' section
cat("\n## By admin area {.tabset}\n")

# Loop through each 'disag_val'
for (disag in params$selected_disag_vals) {
  cat(paste0("\n### ", disag, "{.tabset}\n"))  # Main tab for each 'disag_val'
  
  # Create a sub-tabset for questions inside each 'disag_val' tab
  for (question in params$selected_questions) {
    selected_question <- question  # Ensure explicit variable assignment
    plot_data <- data %>% filter(disag_val_1 == disag, label == selected_question)

    if (nrow(plot_data) > 0) {
      cat(paste0("\n#### ", selected_question, "\n"))  # Sub-tab for each question under this 'disag_val'
      
      # Calling the plot functions based on variable type (e.g., categorical or numerical)
      if (unique(plot_data$q.type) %in% c("select_multiple", "select_one")) {
        p <- plot.select(df = plot_data, var = selected_question, n_min=100)
      } else {
        p <- plot.int(df = data, df_res = plot_data, var = selected_question, )
      }
      
      print(p)  # Display the plot inside the sub-tab
      cat("\n\n")  # Add line breaks for clarity
    }
  }
}


```



```{r generate_indicator_plots old,  results='asis', echo=F, eval=T, message=F}
# Generate plots for Section 2: By Indicator
# cat("\n# By Indicator2 {#indicator}\n")
cat("\n## By indicator {.tabset}\n")

# Main script: process data once and loop through questions & choices
selected_areas <- params$selected_disag_vals

area_data <- data %>% 
  filter(disag_val_1 %in% selected_areas)

for (question in params$selected_questions) {
  selected_question <- question
  cat(paste0("\n### ", question, "{.tabset}\n"))
  
  # Process data once for the given question
  df_filtered <- area_data %>%
    filter(label == selected_question) %>%
    group_by(question, choice) %>%
    summarise(total_percent = round(sum(count) / sum(resp) * 100, 1)) %>%
    slice_max(total_percent, n = 3) %>%
    inner_join(area_data, by = c("question", "choice")) %>%
    group_by(col, label, choice) %>%
    arrange(choice, desc(mean), desc(count)) %>%
    slice_max(count, n = 10)
  
  for (choosen in unique(df_filtered$choice)) {
    df_choice <- df_filtered %>% filter(choice == choosen)
    
    cat(paste0("\n#### ", str_trunc(unique(df_choice$label.choice), 60), "\n"))  # Sub-tab for each choice
    print(plot.ind_comparison(df_choice, choosen))
    cat("\n\n")  # Line breaks for clarity
  }
}

```


```{r generate_indicator_plots,  results='asis', echo=F, eval=T, message=F}
# Generate plots for Section 2: By Indicator
# cat("\n# By Indicator2 {#indicator}\n")
cat("\n## By indicator x Area {.tabset}\n")

# Main script: process data once and loop through questions & choices
selected_areas <- params$selected_disag_vals

area_data <- data %>% 
  filter(disag_val_1 %in% selected_areas)

for (question in params$selected_questions) {
  selected_question <- question
  cat(paste0("\n### ", question, "{.tabset}\n"))
  
  # Process data once for the given question
     data_filtered <- area_data %>% 
      # filter(label == input$selected_question, disag_val_1 %in% input$filter_disag_val_1) %>%
      filter(label ==selected_question, disag_val_1 %in% params$selected_disag_vals) %>%
      group_by(choice) %>% 
      mutate(total_percentage = sum(mean)) %>% ungroup() %>% 
      arrange(desc(total_percentage), desc(mean))
    
    resp_sum <- data_filtered %>% select(disag_val_1, resp) %>% unique() %>% pull(resp) %>% sum()
  
    print(plot_area_comparison(data_filtered))
    cat("\n\n")  # Line breaks for clarity
  
}

```



