---
title: "Data vis report"
output:
  html_document:
    toc: false
    toc_float: false
    theme: flatly
params:
  selected_disag_var: NULL
  selected_disag_vals: NULL
  selected_questions: NULL
  data_file: NULL
editor_options:
  chunk_output_type: console
---

# {.tabset}

```{r setup , include=F}
# library(tidyverse)
# library(openxlsx)
# library(data.table)
knitr::opts_chunk$set(
  echo = FALSE,      # Hide code in the output
  eval = TRUE,       # Ensure all code is executed
  message = FALSE,   # Suppress messages (e.g., from loading packages)
  warning = FALSE,   # Suppress warnings in the output
  results = 'asis',  # Allow raw markdown output (useful for cat())
  # fig.align = "center", # Center align figures
  fig.width = 10,    # Default figure width
  fig.height = 5     # Default figure height
)

local <- interactive() || knitr::is_html_output()  # Adjust based on your case


is_knitting <- !interactive()


if (local==T){
  
# Print the status
if (is_knitting) {
cat("Knitting the R Markdown document.\n")

library(pacman)
p_load(shiny, shinydashboard, writexl, dplyr, readxl, openxlsx, janitor, tidyverse, purrr, data.table, markdown,
       kableExtra, ggridges, corrplot, kableExtra, scico)
source('src/server_functions/functions.R', local=T)
source('src/server_functions/Mode.R', local=T)
source('src/server_functions/process_data_for_aggregation.R', local=T)
source('src/server_functions/aggregate_data.R', local=T)
source('src/server_functions/format.R', local=T)
source('src/server_functions/utils.R', local=T)
source('src/server_functions/si_functions.R', local=T)
  
} else {
cat("Running within a Shiny app.\n")
}
  
}

```


```{r loading data, include=FALSE}
# rm(list=ls())

local <- interactive() || knitr::is_html_output()  # Adjust based on your case


is_knitting <- !interactive()
# knit <- knitr::opts_knit$get("rmarkdown")$input
# local_knit <- T

if (local==T){
  
  # Print the status
  if (is_knitting) {
    cat("Knitting the R Markdown document.\n")
    library(pacman)
    p_load(shiny, shinydashboard, writexl, dplyr, readxl, openxlsx, janitor, tidyverse, purrr, data.table, markdown,
           kableExtra, ggridges, corrplot, kableExtra, scico)
    source('src/server_functions/functions.R', local=T)
    source('src/server_functions/Mode.R', local=T)
    source('src/server_functions/process_data_for_aggregation.R', local=T)
    source('src/server_functions/aggregate_data.R', local=T)
    source('src/server_functions/format.R', local=T)
    source('src/server_functions/utils.R', local=T)
    source('src/server_functions/si_functions.R', local=T)
    
  } else {
    cat("Running within a Shiny app.\n")
  }
  


# cat('Knitting:', local_knit)
# local shiny
# if(local_knit==T){
# data <- readRDS(list.files(pattern="analysis_data.rds", full.names = TRUE))
# }else{
# data <- readRDS(list.files('markdown/',pattern="analysis_data.rds", full.names = TRUE))
# }
# data <- readRDS(list.files(pattern="analysis_data.rds", full.names = TRUE))
data <- readRDS(list.files(pattern="analysis_data.rds", full.names = TRUE))

rm(params)
params <- NULL
params$selected_disag_var <- data %>% select(disag_var_1) %>% unique() %>% pull(disag_var_1)
params$selected_disag_var <- params$selected_disag_var[1]
params$selected_disag_vals <- data %>% select(disag_val_1) %>% unique() %>% pull(disag_val_1)
params$selected_questions <- data %>% select(label) %>% unique() %>% pull(label)
params$selected_questions <- params$selected_questions[1:10]
# params$data_file <- list.files('markdown/',pattern="analysis_data.rds", full.names = TRUE)
}else{
  data <- readRDS(params$data_file)
}

params$selected_disag_vals <- data %>% filter(disag_var_1 == params$selected_disag_var) %>% select(disag_val_1) %>% unique() %>% pull(disag_val_1)

data <- data %>% 
  filter(is.na(choice)==F, is.na(question)==F, is.na(label)==F) %>% 
  filter(disag_var_1==params$selected_disag_var, 
         disag_val_1 %in% params$selected_disag_vals, 
         label %in% params$selected_questions)


if ("All" %in% params$selected_disag_vals){
  params$selected_disag_vals <- data %>% 
    select(disag_val_1) %>% unique() %>% pull(disag_val_1)
}
print(params)


# Initialize lists to store plots
plots_disag_val <- list()
plots_indicator <- list()
```



```{r Area plots old, results='asis', eval=F}
# Main tabset for 'By Disag-Val' section
cat("\n## By admin area {.tabset}\n")

# Loop through each 'disag_val'
for (disag in c("All", params$selected_disag_vals)) {
  cat(paste0("\n### ", disag, "{.tabset}\n"))
  cat("\n\n")  # Add line breaks for clarity
  # Main tab for each 'disag_val'
  if (disag == "All"){
    cat('All contains information on the entire dataset and reflects the overall situation across all areas assessed.\n\n')
  }
  # Create a sub-tabset for questions inside each 'disag_val' tab
  for (question in params$selected_questions) {
    selected_question <- question  # Ensure explicit variable assignment
    if (disag == "All"){
      plot_data <- data %>% filter(label==selected_question) %>% 
        group_by(disag_var_1,q.type, question, label, choice, label.choice) %>% 
        summarise(count = sum(count, na.rm=T), resp = sum(resp, na.rm=T), mean = count/resp)
    }else{
    plot_data <- data %>% filter(disag_val_1 == disag, label == selected_question) %>% 
              group_by(disag_var_1,disag_val_1, q.type,question, label, choice, label.choice) %>% 
        summarise(count = sum(count, na.rm=T), resp = sum(resp, na.rm=T), mean = count/resp)
    }
    if (nrow(plot_data) > 0) {
      cat(paste0("\n#### ", selected_question, "\n"))  # Sub-tab for each question under this 'disag_val'
      
      # Calling the plot functions based on variable type (e.g., categorical or numerical)
      if (unique(plot_data$q.type) %in% c("select_multiple", "select_one")) {
        p <- plot.select(df = plot_data, var = selected_question, n_min=100)
      } else {
        p <- plot.int(df = data, df_res = plot_data, var = selected_question)
      }
      
      print(p)  # Display the plot inside the sub-tab
      cat("\n\n")  # Add line breaks for clarity
    }
  }
}


```



```{r faster area plots, results='asis', eval=T}
# library(data.table)

cat("\n## By admin area {.tabset}\n")

# Convert data to data.table for faster processing
data <- as.data.table(data)

# Prepare a list to store the results
results <- list()

# Function to generate plot data
generate_plot_data <- function(disag, selected_question) {
  if (disag == "All") {
    plot_data <- data[label == selected_question, .(
      count = sum(count, na.rm = TRUE),
      resp = sum(resp, na.rm = TRUE),
      mean = sum(count, na.rm = TRUE) / sum(resp, na.rm = TRUE)
    ), by = .(disag_var_1, q.type, question, label, choice, label.choice)]
  } else {
    plot_data <- data[disag_val_1 == disag & label == selected_question, .(
      count = sum(count, na.rm = TRUE),
      resp = sum(resp, na.rm = TRUE),
      mean = sum(count, na.rm = TRUE) / sum(resp, na.rm = TRUE)
    ), by = .(disag_var_1, disag_val_1, q.type, question, label, choice, label.choice)]
  }
  return(plot_data)
}

# Generate plot data for all combinations of 'disag' and 'selected_question'
for (disag in c("All", params$selected_disag_vals)) {
  cat(paste0("\n### ", disag, "{.tabset}\n"))  # Main tab for each 'disag_val'
    if (disag == "All"){
    cat('All contains information on the entire dataset and reflects the overall situation across all areas assessed.\n\n')
  }
  plot_data_list <- lapply(params$selected_questions, generate_plot_data, disag = disag)
  
  for (i in seq_along(plot_data_list)) {
    plot_data <- plot_data_list[[i]]
    selected_question <- params$selected_questions[i]
    
    if (nrow(plot_data) > 0) {
      cat(paste0("\n#### ", selected_question, "\n"))  # Sub-tab for each question under this 'disag_val'
      
      # Calling the plot functions based on variable type (e.g., categorical or numerical)
      if (unique(plot_data$q.type) %in% c("select_multiple", "select_one")) {
        p <- plot.select(df = plot_data, var = selected_question, n_min = 100)
      } else {
        p <- plot.int(df = data, df_res = plot_data, var = selected_question)
      }
      
      print(p)  # Display the plot inside the sub-tab
      cat("\n\n")  # Add line breaks for clarity
    }
  }
}


```



```{r generate_indicator_plots old,  results='asis', echo=F, eval=T, message=F}
# Generate plots for Section 2: By Indicator
# cat("\n# By Indicator2 {#indicator}\n")
cat("\n## By indicator {.tabset}\n")

# Main script: process data once and loop through questions & choices
selected_areas <- params$selected_disag_vals

area_data <- data %>% 
  filter(disag_val_1 %in% selected_areas)

for (question in params$selected_questions) {
  selected_question <- question
  cat(paste0("\n### ", question, "{.tabset}\n"))
  

  # Process data once for the given question
  df_filtered <- area_data %>%
    filter(label == selected_question) %>%
    group_by(question, choice) %>%
    summarise(total_percent = round(sum(count) / sum(resp) * 100, 1)) %>%
    slice_max(total_percent, n = 3) %>%
    inner_join(area_data, by = c("question", "choice")) %>%
    group_by(col, label, choice) %>%
    arrange(choice, desc(mean), desc(count)) %>%
    slice_max(count, n = 10)
  
  if (nrow(df_filtered) > 0) {
  
  for (choosen in unique(df_filtered$choice)) {
    df_choice <- df_filtered %>% filter(choice == choosen)
        if (nrow(df_choice) > 0) {

    cat(paste0("\n#### ", str_trunc(unique(df_choice$label.choice), 60), "\n"))  # Sub-tab for each choice
    print(plot.ind_comparison(df_choice, choosen))
    cat("\n\n")  # Line breaks for clarity
        }
  }
  }
}

```


```{r generate_indicator_plots,  results='asis', echo=F, eval=T, message=F}
# Generate plots for Section 2: By Indicator
# cat("\n# By Indicator2 {#indicator}\n")
cat("\n## By indicator x Area {.tabset}\n")

# Main script: process data once and loop through questions & choices
selected_areas <- params$selected_disag_vals

area_data <- data %>% 
  filter(disag_val_1 %in% selected_areas)

for (question in params$selected_questions) {
  selected_question <- question
  cat(paste0("\n### ", question, "{.tabset}\n"))
  
  # Process data once for the given question
     data_filtered <- area_data %>% 
      # filter(label == input$selected_question, disag_val_1 %in% input$filter_disag_val_1) %>%
      filter(label ==selected_question, disag_val_1 %in% params$selected_disag_vals) %>%
      group_by(choice) %>% 
      mutate(total_percentage = sum(mean)) %>% ungroup() %>% 
      arrange(desc(total_percentage), desc(mean))
    
    if (nrow(data_filtered) > 0) {
     
    resp_sum <- data_filtered %>% select(disag_val_1, resp) %>% unique() %>% pull(resp) %>% sum()
  
    print(plot_area_comparison(data_filtered))
    cat("\n\n")  # Line breaks for clarity
    }
}

```




```{r Area plots basic, results='asis', eval=F}

cat("\n## By admin area {.tabset}\n")

# Convert data to data.table for faster processing
data <- as.data.table(data)

# Loop through each 'disag_val'
for (disag in c("All", params$selected_disag_vals)) {
  cat(paste0("\n### ", disag, "{.tabset}\n"))  # Main tab for each 'disag_val'
  
  # Create a sub-tabset for questions inside each 'disag_val' tab
  for (question in params$selected_questions) {
    selected_question <- question  # Ensure explicit variable assignment
    if (disag == "All") {
      plot_data <- data[label == selected_question, .(
        count = sum(count, na.rm = TRUE),
        resp = sum(resp, na.rm = TRUE),
        mean = sum(count, na.rm = TRUE) / sum(resp, na.rm = TRUE)
      ), by = .(disag_var_1, q.type, question, label, choice, label.choice)]
      cat('All contains information on the entire dataset and reflects the overall situation across all areas assessed.\n\n')
    } else {
      plot_data <- data[disag_val_1 == disag & label == selected_question, .(
        count = sum(count, na.rm = TRUE),
        resp = sum(resp, na.rm = TRUE),
        mean = sum(count, na.rm = TRUE) / sum(resp, na.rm = TRUE)
      ), by = .(disag_var_1, disag_val_1, q.type, question, label, choice, label.choice)]
    }
    if (nrow(plot_data) > 0) {
      cat(paste0("\n#### ", selected_question, "\n"))  # Sub-tab for each question under this 'disag_val'
      
      # Calling the plot functions based on variable type (e.g., categorical or numerical)
      if (unique(plot_data$q.type) %in% c("select_multiple", "select_one")) {
        p <- plot.select(df = plot_data, var = selected_question, n_min = 100)
      } else {
        p <- plot.int(df = data, df_res = plot_data, var = selected_question)
      }
      
      print(p)# Display the plot inside the sub-tab
                
      cat("\n\n") # Add line breaks for clarity
    }
  }
}

```



